---
# Listing of data to be read from marc bibliographic data
#
# Format is:
# <name of the data set>:
#   category:               <categories corresponding to categories chosen in the core-template>
#                               title should be set; other categories are mandatory
#   originalletters:        <yes|no> whether item in original letters should be
#                               shown or not (see marc 880)
#   <main field>:           at least one should be set; fields with a leading 0 should be quoted
#                               if only parent methods are used the main field is '000'
#     conditions:           conditions which should be fulfilled if the data is read
#       - [<item>, <key>, <value>]          <item> is either field or indicator
#                                           <key> is the name of the field or indicator
#                                           <value> is the value it should have
#     parent:               use a parent method (from SolrDefault driver)
#       - [<method name>]       the method to use
#     subfields:            only read the fields
#       - [<field list>]        list of fields to read
#     <subfield>:           enhanced processing of a subfield
#       - [name, <name>]                     name it
#       - [replace, <from>, <to>]            replace a substring from <from> to <to> (using a regex)
#       - [match, <what>, <which>]           match a substring (<what>) and use the <which>th parantesis
#                                                (using a regex)
#       - [function, <php-function>]         use th return value of a php-function
#
#-----------------------------------------------------------------------------------
#

# example configuration

# mandatory
Format:
  category: description
  '000':
    parent:
      - [method, getFormats]
# mandatory
Signature:
  category: delivery
  980:
    conditions:
      - [field, 2, '^22$']
    d:
      - [name, signature]
    e:
      - [name, indicator]
    f:
      - [name, sigel]
    k:
      - [name, footnote]
    x:
      - [name, licencenote]
    y:
      - [name, locationnote]
# only if licence criteria are set in deliveryAvailability.ini
Licence:
  category: delivery
  981:
    conditions:
      - [field, 2, '^22$']
    y:
      - [name, licencetype]
# this and the following are going to be made configurable soon
DeliveryDataArticle:
  category: delivery
  '000':
    parent:
      - [method, getUniqueId]
      - [name, article-ppn]
  245:
    a:
      - [name, article-title]
  100:
    a:
      - [name, article-author]
  773:
    conditions:
      - [field, w, 'DE-627']
    w:
      - [name, ppn]
      - [replace, '\(.+\)', '']
    t:
      - [name, title]
    g:
      - [name, volume-year-pages]
  980:
    conditions:
      - [field, 2, '^22$']
    d:
      - [name, signature]
DeliveryDataSerialVolume:
  category: delivery
  '000':
    parent:
      - [method, getUniqueId]
      - [name, ppn]
  245:
    a:
      - [name, title]
    c:
      - [name, title]
    n:
      - [name, title]
    p:
      - [name, title]
  490:
    a:
      - [name, title]
  980:
    conditions:
      - [field, 2, '^22$']
    d:
      - [name, signature]
DeliveryDataJournal:
  category: delivery
  '000':
    parent:
      - [method, getUniqueId]
      - [name, ppn]
  245:
    a:
      - [name, title]
    c:
      - [name, title]
    n:
      - [name, title]
    p:
      - [name, title]
  490:
    a:
      - [name, title]
  980:
    conditions:
      - [field, 2, '^22$']
    d:
      - [name, signature]
DeliveryData:
  category: delivery
  '000':
    parent:
      - [method, getUniqueId]
      - [name, ppn]
  245:
    a:
      - [name, title]
    c:
      - [name, title]
  980:
    conditions:
      - [field, 2, '^22$']
    d:
      - [name, signature]
